sources:
  - name: StackExchange
    handler:
      openapi:
        source: https://raw.githubusercontent.com/grokify/api-specs/master/stackexchange/stackexchange-api-v2.2_openapi-v3.0.yaml
  - name: Authzed
    handler:
      grpc:
        endpoint: grpc.authzed.com:443
        metaData:
          token: 'some_token'
          connection_type: ['headers', 'connection']
        protoFilePath:
          file: ./v1/permission_service.proto
          load:
            includeDirs:
              - ./v1